
---
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn lint
  publish:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: publish
          command: |
            git config user.email "build@circleci.com"
            git config user.name "CircleCI"
            ./node_modules/exp/bin/exp.js login -u $EXP_USERNAME -p $EXP_PASSWORD
            sudo npm install -g npm-cli-login
            npm-cli-login
workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
