
---
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn lint
  release:
    docker:
      - image: circleci/node:8.1.4
      - checkout
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn release
workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
