
---
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'export PATH=/foo/bin:$PATH' >> $BASH_ENV
      - run: echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn lint
  publish:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn publish
workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
